name: Scala SBT with Snyk Open Source Test
on: push
jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Cache SBT dependencies
    - name: Cache SBT Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier
        key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          sbt-${{ runner.os }}-

    # Run SBT tests
    - name: Run SBT Tests
      run: sbt test
  
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/sbt1.10.0-scala3.4.2@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    # Run Snyk Open Source Test
    - name: Run Snyk Open Source Test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
